// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109115637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Entities.FeedingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("FeedingSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Incompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetBId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetAId");

                    b.HasIndex("PetBId");

                    b.ToTable("Incompatibilities");
                });

            modelBuilder.Entity("Domain.Entities.Kennel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjacentKennelIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleaningStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleaningUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentPetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("Domain.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Domain.Entities.MedicationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Given")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GivenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffInitials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("MedicationLogs");
                });

            modelBuilder.Entity("Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremiumLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aggressive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Species")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Domain.Entities.PhotoUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SentToOwner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdateType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PhotoUpdates");
                });

            modelBuilder.Entity("Domain.Entities.Stay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleaningUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KennelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KennelId");

                    b.HasIndex("PetId");

                    b.ToTable("Stays");
                });

            modelBuilder.Entity("Domain.Entities.FeedingSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("FeedingSchedules")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.Incompatibility", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "PetA")
                        .WithMany()
                        .HasForeignKey("PetAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pet", "PetB")
                        .WithMany()
                        .HasForeignKey("PetBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetA");

                    b.Navigation("PetB");
                });

            modelBuilder.Entity("Domain.Entities.Kennel", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "CurrentPet")
                        .WithMany()
                        .HasForeignKey("CurrentPetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPet");
                });

            modelBuilder.Entity("Domain.Entities.Medication", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("Medications")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.MedicationLog", b =>
                {
                    b.HasOne("Domain.Entities.Medication", "Medication")
                        .WithMany("Logs")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Domain.Entities.Pet", b =>
                {
                    b.HasOne("Domain.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.PhotoUpdate", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("PhotoUpdates")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.Stay", b =>
                {
                    b.HasOne("Domain.Entities.Kennel", "Kennel")
                        .WithMany("Stays")
                        .HasForeignKey("KennelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("Stays")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kennel");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.Kennel", b =>
                {
                    b.Navigation("Stays");
                });

            modelBuilder.Entity("Domain.Entities.Medication", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Domain.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Domain.Entities.Pet", b =>
                {
                    b.Navigation("FeedingSchedules");

                    b.Navigation("Medications");

                    b.Navigation("PhotoUpdates");

                    b.Navigation("Stays");
                });
#pragma warning restore 612, 618
        }
    }
}
